### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by terry47** [Wiredcraft/lunr-chinese#1]
Hi there, 
I've got below error when I install lunr-chinese. I created a separate folder for the installation. 
I'm sure "lunr": "~2.1.5" and "nodejieba": "~2.2.5" have been installed correctly but still got error. 
Any suggestion? 

**ERROR**
 Error: No compatible version found: nodejieba@'^2.2.5'

Thanks 

Terry

**Comment by ole3021** [comment]
Hi @terry47 

The `lunr-chinese` build based on `lunr v0.7.2` and `nodejieba ^2.2.5` which means it only works with lunr 0.7.2

> After you generate the tokenize file, you have to load it back to lunr 0.7.2 instance to make it work.

The reason it use lunr 0.7.2 instead of the lasted V2 version is caused lunr has updated the tokenize method in the V2 which is a more effective way but for English only. To deal with Chinese the lunr 0.7.2 are the only supported version. 

For more details please check the [Readme](https://github.com/Wiredcraft/lunr-chinese/blob/master/README.md) out.

**Comment by terry47** [comment]
Hi ole3021,

Thanks
